services:
  postgres:
    image: postgres:17
    container_name: pokemon-postgres
    restart: always
    environment:
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_password
      POSTGRES_DB: pokemon_game
    ports:
      - "5433:5432"
    volumes:
      - pokemon_data:/var/lib/postgresql/data

volumes:
  pokemon_data: